# Generated by Django 5.0.6 on 2024-06-25 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaminvitation',
            old_name='isAccepted',
            new_name='is_accepted',
        ),
        migrations.AddConstraint(
            model_name='teaminvitation',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='unique_team_invitation'),
        ),
    ]
